export { default as Input } from './Input/Input';
export { default as Button } from './Button/Button';
export { default as Avatar } from './Avatar/Avatar';
export { default as Checkbox } from './Checkbox/Checkbox';
export { default as SidebarButton } from './SidebarButton/SidebarButton';
export { default as Table } from './Table/Table';
export { default as Select } from './Select/Select';
export { default as AdaptationCalendar } from './AdaptationCalendar/AdaptationCalendar';
import dynamic from 'next/dynamic';
export const CKEditorField = dynamic(() => import('./CKEditorField/CKEditorField'), { ssr: false });
export { default as StatCard } from './StatCard/StatCard';
export { default as CallCardTrainer } from './trainers/CallCardTrainer/CallCardTrainer';
export type { CallCardResult } from './trainers/CallCardTrainer/CallCardTrainer';