export { default as Input } from './Input/Input';
export { default as Button } from './Button/Button';
export { default as Avatar } from './Avatar/Avatar';
export { default as Checkbox } from './Checkbox/Checkbox';
export { default as SidebarButton } from './SidebarButton/SidebarButton';
export { default as Table } from './Table/Table';
export { default as Select } from './Select/Select';
export { default as AdaptationCalendar } from './AdaptationCalendar/AdaptationCalendar';
import dynamic from 'next/dynamic';
export const CKEditorField = dynamic(() => import('./CKEditorField/CKEditorField'), { ssr: false });
export { default as StatCard } from './StatCard/StatCard';
export { default as CallCardTrainer } from './trainers/CallCardTrainer/CallCardTrainer';
export type { CallCardResult } from './trainers/CallCardTrainer/CallCardTrainer';
export { default as CaseQuizTrainer } from './trainers/CaseQuizTrainer/CaseQuizTrainer';
export { default as PricingQuizTrainer } from './trainers/PricingQuizTrainer/PricingQuizTrainer';
export { default as NewOrderTrainer } from './trainers/NewOrderTrainer/NewOrderTrainer';
export { default as FullOrderCreate } from './trainers/FullOrderCreate/FullOrderCreate';
export { default as AdaptationContent } from './AdaptationContent/AdaptationContent';
export { default as CallsContent } from './CallsContent/CallsContent';
export { default as MentorChart } from './MentorChart/MentorChart';
export { default as InternStatsWidget } from './InternStatsWidget/InternStatsWidget';
export { default as InternProgressWidget } from './InternProgressWidget/InternProgressWidget';
export { default as CourseProgressWidget } from './CourseProgressWidget/CourseProgressWidget';